// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllAccounts() {
  return window['go']['main']['App']['GetAllAccounts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MakeAccount(arg1, arg2) {
  return window['go']['main']['App']['MakeAccount'](arg1, arg2);
}
