// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllAccounts():Promise<Array<main.Account>>;

export function Greet(arg1:string):Promise<string>;

export function MakeAccount(arg1:string,arg2:string):Promise<string>;
